services:
  - type: web
    name: sryzan-backend
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /api/restaurants
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: PORT
        value: 4000